name: GraalVM Native Image builds
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    name: Java-format-service on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file_ext: ""
            arch: linux-amd64
          - os: windows-latest
            file_ext: ".exe"
            arch: win32-amd64
          # - os: macos-latest
          #   file_ext: ""
          #   arch: darwin-aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '20'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build
        run: |
          mvn -Pnative clean package
      - name: Upx
        uses: svenstaro/upx-action@v2
        with:
          files: |
            target/java-format-service${{ matrix.file_ext }}
          args: -o target/java-format-service_${{ matrix.arch }}${{ matrix.file_ext }}
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: |
            target/java-format-service_${{ matrix.arch }}${{ matrix.file_ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish jar
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.os }} == 'ubuntu-latest'
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: |
            target/java-format-service.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
