name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Java-format-service on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build
        run: |
          mvn -Pnative clean package
          upx target/java-format-service
      
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-${{ matrix.os }}
          path: target/java-format-service
